// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gamedetails} from '../models';

export function GetGameDetails(arg1:number):Promise<gamedetails.GetGameDetailOutput>;
