// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {igdb} from '../models';

export function Search(arg1:string):Promise<igdb.VGTSearchResults>;
