// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SearchMainGames(arg1) {
  return window['go']['controllers']['IgdbController']['SearchMainGames'](arg1);
}
