// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {steam} from '../models';

export function GetOwnedGames(arg1:string):Promise<steam.OwnedGamesResponse>;
