// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConfig() {
  return window['go']['backend']['ConfigController']['GetConfig']();
}

export function RefreshConfig() {
  return window['go']['backend']['ConfigController']['RefreshConfig']();
}

export function UpdateConfig(arg1) {
  return window['go']['backend']['ConfigController']['UpdateConfig'](arg1);
}
