// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {config} from '../models';
import {backend} from '../models';

export function GetConfig():Promise<config.Config>;

export function RefreshConfig():Promise<void>;

export function UpdateConfig(arg1:backend.UpdateConfigInput):Promise<config.Config>;
