// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Config { twitch_client_id: string, twitch_client_secret: string, theme: "Light" | "Dark", }