ALTER TABLE game_details ADD COLUMN created_at DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE game_details ADD COLUMN updated_at DATETIME DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE game_details ADD COLUMN is_owned BOOLEAN DEFAULT 0;
ALTER TABLE game_details ADD COLUMN is_beaten BOOLEAN DEFAULT 0;
ALTER TABLE game_details ADD COLUMN is_wishlisted BOOLEAN DEFAULT 0;
