// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GameSummary } from "./GameSummary";

export type SearchGamesOutput = { games: Array<GameSummary>, };