// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function ReadProfile():Promise<models.ReadProfileOutput>;

export function UpdateProfile(arg1:models.UpdateProfileInput):Promise<models.UpdateProfileOutput>;
