name: Wails build

on:
  push:
  pull_request:
    branches: [main]

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        build:
          - name: "VGTracker"
            platform: "linux/amd64"
            os: "ubuntu-latest"
          # - name: 'App'
          #   platform:  'windows/amd64'
          #   os: 'windows-latest'
          - name: "VGTracker"
            platform: "darwin/amd64"
            os: "macos-latest"

    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.2

      - uses: dAppServer/wails-build-action@main
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          go-version: "1.24"
          node-version: "20.x"
