name: Build

on:
  push:
    branches: [main]

jobs:
  linting:
    uses: ./.github/workflows/lint.yaml

  testing:
    uses: ./.github/workflows/test.yaml

  build:
    needs: [linting, testing]
    strategy:
      fail-fast: true
      matrix:
        build:
          - name: "VGTracker"
            platform: "linux/amd64"
            os: "ubuntu-latest"
          # - name: 'App'
          #   platform:  'windows/amd64'
          #   os: 'windows-latest'
          - name: "VGTracker"
            platform: "darwin/amd64"
            os: "macos-latest"

    runs-on: ${{ matrix.build.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.2

      - uses: dAppServer/wails-build-action@main
        with:
          build-name: ${{ matrix.build.name }}
          build-platform: ${{ matrix.build.platform }}
          go-version: "1.24"
          package: true
          node-version: "20.x"

  tag_and_release:
    name: "Tag and Release"
    needs: build
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    steps:
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # - name: list it all in UPLOAD step
      #   run: ls -la

      - uses: actions/download-artifact@v4
        with:
          path: artifacts_download
      - name: Display structure of downloaded files
        run: ls -R

      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
          replacesArtifacts: false
          generateReleaseNotes: true
          artifacts: |
            artifacts_download/*.zip

          # Wails Build macOS VGTracker.zip
          # Wails Build Linux VGTracker.zip
