name: Linting
on:
  workflow_call:

permissions:
  contents: read

jobs:
  backend_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.64.5
          args: --verbose --timeout=5m
          working-directory: backend

  frontend_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.2

      - name: install dependencies
        working-directory: frontend
        run: bun install

      - name: eslint
        working-directory: frontend
        run: bun run ui:lint
