name: Testing

on:
  workflow_call:

permissions:
  contents: read

jobs:
  test_backend:
    name: Run Go Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ ubuntu-latest, windows-latest, macos-latest ]
        os: [ubuntu-latest]
        go-version: ["1.24"]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Steup G
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Get Ginkgo
        run: go install github.com/onsi/ginkgo/v2/ginkgo@v2.22.2

      - name: Run Tests
        run: ginkgo -r

  test_frontend:
    name: Run UI tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.2

      - name: Install dependencies
        run: bun install
        working-directory: frontend

      - name: Run tests
        run: bun run test:unit:ci
        working-directory: frontend
